version: "3.7"
services:

  ## PHP Container ############
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php
    container_name: projeto-restaurante-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - api-projeto-restaurante-network

  ## NGINX Container #############
  nginx:
    image: nginx:1.19-alpine
    container_name: projeto-restaurante-nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api-projeto-restaurante-network
    depends_on:
      - php
      
networks:
  api-projeto-restaurante-network:
    external: true
    name: network_api
