version: '3.7'

services:
  app:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - network-api

  php:
    build: .
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9001:9000"
    networks:
      - network-api

networks:
  network-api:
    external: true
    name: network_api
